# Netlify Configuration for Client Deployment

[build]
  # Base directory is set to "client" in Netlify UI
  # Build command - go to root, install deps, and build
  command = "cd .. && npm install && npm run build:client"
  
  # Publish directory - relative to base directory (client)
  # Since base directory is "client", publish directory is just "dist"
  publish = "dist"
  
  # Environment variables to include in build
  [build.environment]
    NODE_VERSION = "20"

# SPA (Single Page Application) redirect rules
# This ensures all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify UI)
# VITE_API_URL = "https://your-render-app.onrender.com"
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
