[build]
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/m/*"
  to = "https://full-links.onrender.com/m/:splat"
  status = 302

[[redirects]]
  from = "/e/*"
  to = "https://full-links.onrender.com/e/:splat"
  status = 302

[[redirects]]
  from = "/z/*"
  to = "https://full-links.onrender.com/z/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"